language: rust
os: linux
dist: xenial

cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - (test -x $HOME/.cargo/bin/wasm-pack || cargo install --vers "^0.9" wasm-pack)
  - cargo install-update -a

script:
  - cd $TRAVIS_BUILD_DIR; make


deploy:
  strategy: git
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: $TRAVIS_BUILD_DIR/book
  keep_history: false
  on:
    branch: master
