[book]
authors = ["sdfgeoff"]
language = "en"
multilingual = false
src = ""
title = "wasm_games_in_rust"

[build]
create-missing = false


[output.html]
additional-css = ["gen/book_extra.css"]
additional-js = ["gen/book_extra.js"]
