[book]
authors = ["sdfgeoff"]
language = "en"
multilingual = false
src = "content"
title = "wasm_games_in_rust"

[build]
create-missing = false


[output.html]
additional-css = ["content/book_extra.css"]
additional-js = ["content/book_extra.js"]
