name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install mdbook
      run: test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook
      
    - name: Install WasmPack
      run: test -x $HOME/.cargo/bin/wasm-pack || cargo install --vers "^0.10.3" wasm-pack

    - name: Build
      run: make

    - name: Upload To Github Pages
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        # Path of the directory containing the static assets.
        path: /bin_book
